version: 1.0.{build}
build_script:
- cmd: >-
    set path=%path:C:\Program Files\Git\usr\bin=%

    set path=%path%;C:\MinGW\bin

    gcc -v

    perl -v

    perl Makefile.PL MAKE=gmake

    mingw32-make test
